### ISSUE TITLE
Recaptcha not validating

### ISSUE THREAD

**Issue by sahilsharma011** [greggilbert/recaptcha#84] opened 2015-08-05 09:36 UTC
I have followed each and every step as it was suggested in the docs, I typed in the correct keys in correct places and in the starting days it was working fine.
But after some days it is not validating the user and it is saying that user is not a human.

**Comment by pflirae** [comment] 2015-08-11 16:16
I have a similar situation, I have to enter more that 4 times the captach to finaly and "magically" be able to login.

**Comment by jeffer8a** [comment] 2015-08-26 18:49
any solution for this ?

**Comment by greggilbert** [comment] 2015-08-31 03:39
Hmm.. I'd need a bit more information about the situation. Can you tell if the request is going out to Recaptcha and coming back invalid, or is it failing earlier? Are your keys correct? How can I reproduce this issue?

**Comment by jeffer8a** [comment] 2015-08-31 11:05
apparently the problem is the recaptcha validation rule. In the front everything works just fine, but when I submit the form, the "recaptcha" validation throws the same error over and over

**Comment by pflirae** [comment] 2015-09-01 19:30
After doing some research on this problem I have been able to verify that the root cause is a timeout condition when calling the verification site using curl. To solve it I have changed the default time out value from 1 to 2 seconds on the config/recaptcha.php file, and now it is working fine. Will continue monitoring this issue for a couple of days to confirm that this is the solution.

**Comment by KalinKanev** [comment] 2015-09-05 15:13
I can confirm the timeout issue. Have lost couple of hours trying to cope with this. Big thanks !

**Comment by pflirae** [comment] 2015-09-06 21:23
Since my last comment, recaptcha has been working without problems, so the problem was the timeout and is solved increasing it to 2 seconds. From my perspective tha problem is solved.

**Comment by KalinKanev** [comment] 2015-09-07 07:41
Indeed but I think more informative error about the timeout is crucial here.

**Comment by nasirkhan** [comment] 2015-09-23 08:06
faced the similar situation. it was working properly and today while i was building a new form it did not work there. then i checked the previous forms and none of these were working at all. form frontend shows that recaptcha is validated, but server response shows that i am not a human!

**Comment by drtzack** [comment] 2015-09-24 10:35
Same here. It works good in my local env but doesn't work in production.

**Comment by drtzack** [comment] 2015-09-24 10:38
I think CURL can cause that.

**Comment by sonuku** [comment] 2015-09-24 22:29
Try upping the curl timeout?

**Comment by drtzack** [comment] 2015-09-24 22:51
Changing driver to native from CURL is works. 

Also I don't know how but just solved it for CURL.

When I tried to work with CURL it wanted me to add something in php.ini after that It worked.

**Comment by greggilbert** [comment] 2015-10-21 03:05
Okay, so it's a curl and/or timeout issue. Closing.

**Closed by greggilbert** 2015-10-21 03:05 UTC
